apiVersion: v1
kind: PersistentVolume
metadata:
   name: apim-rdbms-volume
spec:
   capacity:
     storage: 20Gi
   accessModes:
     - ReadWriteOnce
   nfs:
     path: /var/exports/rdbms
     server: 10.111.3.105
   persistentVolumeReclaimPolicy: Retain
